dataloader:
  #  ['covidNJ', 'earthquakesJP', 'shakyHawkes', 'delayPeak', 'shiftHawkes']
  name: ['delayPeak']
trained_model:
  name: ['autoint']
  # name: ['autoint-gru']
  hidden_size: [32]
  lr: 0.01 
  n_epoch: 100
  n_eval_epoch: 10
  retrain: true